name = "sprocket_starter"
version = "0.0.1"
description = "Example starter app for Sprocket, a library for building live views and real-time server components in Gleam"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licenses = ["MIT"]
repository = { type = "github", user = "bitbldr", repo = "sprocket_starter" }
links = [{ title = "Website", href = "https://sprocket.live" }]
gleam = ">= 1.0.0"

# Modules that should be considered "internal" and will not be included in
# generated documentation. Note this currently only affects documentation;
# public types and functions defined in these modules are still public.
#
# Items in this list are "globs" that are matched against module names. See:
# https://docs.rs/glob/latest/glob/struct.Pattern.html
#internal_modules = [
#  "sprocket_starter/internal",
#]

[dependencies]
gleam_stdlib = ">= 0.55.0 and < 1.0.0"
gleam_http = "~> 3.6"
mist = "~> 4.0.0"
sprocket = "~> 2.0.0"
sprocket_mist = "~> 2.0.0"
gleam_erlang = ">= 0.32.0 and < 1.0.0"
gleam_json = ">= 2.1.0 and < 3.0.0"
gleam_crypto = "~> 1.3"
gleam_otp = ">= 0.14.1 and < 1.0.0"
ids = "~> 0.10"
simplifile = "~> 1.5"
envoy = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
